### ISSUE TITLE
Лишний suspend

### ISSUE THREAD

**Issue by Unrealf1** [mipt-npm/genphys-diffraction#3]
Кажется, что модификатор suspend тут ни к чему

https://github.com/mipt-npm/genphys-diffraction/blob/1de0f40e97bf30e4b468bff2ebb777d4a995d6f8/src/commonMain/kotlin/ru/mipt/phys/diffraction/DiffractionCalculator.kt#L38

**Comment by altavir** [comment]
Это я поставил на случай, если мы это когда-нибудь будем параллелить, чтобы потом не ломать API
